### ISSUE TITLE
Guy,Add a support for Touch Streen kmdf hid minidriver for touch I2C Device,please?

### ISSUE THREAD

**Issue by Kissycat** [PhoenixOS/kernel#1]
Hardware ID:
ACPI\VEN_MSSL&DEV_1680
ACPI\MSSL1680
*MSSL1680

**Comment by edward-p** [comment]
Same request for me. This is Silead Touch Screen. There is already a moudule `silead_ts` in Linux 4.9+. And available firmware [here](https://github.com/edward-p/mssl1680-firmware).I have already get my touch screen work on Arch Linux. But I'm not familiar with Android X86. My Tablet is [Teclast X5 Pro](https://wiki.archlinux.org/index.php/Teclast_X5_Pro). Please help.

**Comment by beacool** [comment]
We are still waiting to support kmdf hid minidriver for touch I2C Device
